### ISSUE TITLE
i use  four threads to update a table,and sometimes ,it happends

### ISSUE THREAD

**Issue by ccccccmd** [zzzprojects/EntityFramework.Extended#223]
System.ArgumentException: 已添加了具有相同键的项。     在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)     在 System.Linq.Dynamic.ClassFactory.GetDynamicClass(IEnumerable`1 properties)     在 System.Linq.Dynamic.ExpressionParser.ParseNew()     在 System.Linq.Dynamic.ExpressionParser.ParseIdentifier()     在 System.Linq.Dynamic.ExpressionParser.ParsePrimary()     在 System.Linq.Dynamic.ExpressionParser.ParseUnary()     在 System.Linq.Dynamic.ExpressionParser.ParseMultiplicative()     在 System.Linq.Dynamic.ExpressionParser.ParseAdditive()     在 System.Linq.Dynamic.ExpressionParser.ParseComparison()     在 System.Linq.Dynamic.ExpressionParser.ParseLogicalAnd()     在 System.Linq.Dynamic.ExpressionParser.ParseLogicalOr()     在 System.Linq.Dynamic.ExpressionParser.ParseExpression()     在 System.Linq.Dynamic.ExpressionParser.Parse(Type resultType)     在 System.Linq.Dynamic.DynamicQueryable.Select(IQueryable source, String selector, Object[] values)     在 EntityFramework.Batch.SqlServerBatchRunner.GetSelectSql[TEntity](ObjectQuery`1 query, EntityMap entityMap, DbCommand command)     在 EntityFramework.Batch.SqlServerBatchRunner.Update[TEntity](ObjectContext objectContext, EntityMap entityMap, ObjectQuery`1 query, Expression`1 updateExpression)     在 EntityFramework.Extensions.BatchExtensions.Update[TEntity](IQueryable`1 source, Expression`1 updateExpression)

**Comment by JonathanMagnan** [comment]
Hello @ccccccmd  ,

This library is no longer supported since 2015.

We recommend you to move to [Entity Framework Plus](http://entityframework-plus.net/) which is also a free & open source library.

This issue have good chance to already be solved in EF+

Best Regards,

Jonathan
